name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "* * * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Retry on Bad Gateway
        run: |
          while true; do
              response=$(curl -k -f https://www.pilotdog.tech/api/get_eligible_proof?address=0x0D548b394f2d7be11f511606339A1E80a70A35a1 2>&1)
              if [[ $response == *"502 Bad Gateway"* ]]; then
                  echo "Received Bad Gateway error. Retrying in 60 seconds..."
                  sleep 60
              else
                  echo "Request successful."
                  echo "$response" > Update.ts
                  break
              fi
          done
          
      - name: Commit changes
        run: |
          git config --local user.email "contact@megumii.xyz"
          git config --local user.name "Megumiiiiii"
          git add -A
          
          arr[0]="chore(bot): 😂 auto commit"
          arr[1]="chore(bot): 😱 auto commit"
          arr[2]="chore(bot): 👿 auto commit"
          arr[3]="chore(bot): 💩 auto commit"
          arr[4]="chore(bot): 🙏 auto commit"
          arr[5]="chore(bot): 🙈 auto commit"
          arr[6]="chore(bot): 🐐 auto commit"
          arr[7]="chore(bot): 🤖 auto commit"
          arr[8]="chore(bot): 🟩 auto commit"
          arr[9]="chore(bot): 👻 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
